export const PICTURE_SELECTED = "PICTURE_SELECTED";
export const FRAME_SELECTED = "FRAME_SELECTED";
export const TEXT_HEADING_UPDATED = "TEXT_HEADING_UPDATED";
export const TEXT_SIGNATURE_UPDATED = "TEXT_SIGNATURE_UPDATED";
export const TEXT_DATE_UPDATED = "TEXT_DATE_UPDATED";

export const FONT_CHANGED = "FONT_CHANGED";

export const FINGERPRINT_SELECTED = "FINGERPRINT_SELECTED";

export const PHONE_NUMBER_UPDATED = "PHONE_NUMBER_UPDATED";

export const ENABLE_PURCHASE = "ENABLE_PURCHASE";
export const DISABLE_PURCHASE = "DISABLE_PURCHASE";

export const SUBMIT_ORDER_START = "SUBMIT_ORDER_START";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_FAILED = "SUBMIT_ORDER_FAILED";

export const ERACE_APP_DATA = "ERACE_APP_DATA";

export const FIX_ERROR_TRYHARD_XD = "FIX_ERROR_TRYHARD_XD";
